//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AKSHManageEntities : DbContext
    {
        public AKSHManageEntities()
            : base("name=AKSHManageEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_Dictionary> M_Dictionary { get; set; }
        public virtual DbSet<M_DictionaryType> M_DictionaryType { get; set; }
        public virtual DbSet<M_PatientCharge> M_PatientCharge { get; set; }
        public virtual DbSet<M_PatientRecordCPR> M_PatientRecordCPR { get; set; }
        public virtual DbSet<M_PatientRecordDiag> M_PatientRecordDiag { get; set; }
        public virtual DbSet<M_PatientRecordECGImpressions> M_PatientRecordECGImpressions { get; set; }
        public virtual DbSet<M_PatientRecordTrace> M_PatientRecordTrace { get; set; }
        public virtual DbSet<M_ZECGImpression> M_ZECGImpression { get; set; }
        public virtual DbSet<M_ZPatientState> M_ZPatientState { get; set; }
        public virtual DbSet<M_ZSymptomPendingInvestigation> M_ZSymptomPendingInvestigation { get; set; }
        public virtual DbSet<P_Department> P_Department { get; set; }
        public virtual DbSet<P_Permission> P_Permission { get; set; }
        public virtual DbSet<P_Role> P_Role { get; set; }
        public virtual DbSet<P_RolePermission> P_RolePermission { get; set; }
        public virtual DbSet<P_SpeicalPermission> P_SpeicalPermission { get; set; }
        public virtual DbSet<P_User> P_User { get; set; }
        public virtual DbSet<P_UserRole> P_UserRole { get; set; }
        public virtual DbSet<TDictionary> TDictionaries { get; set; }
        public virtual DbSet<TDictionaryType> TDictionaryTypes { get; set; }
        public virtual DbSet<I_Delivery> I_Delivery { get; set; }
        public virtual DbSet<I_DeliveryDetail> I_DeliveryDetail { get; set; }
        public virtual DbSet<I_Entry> I_Entry { get; set; }
        public virtual DbSet<I_EntryDetail> I_EntryDetail { get; set; }
        public virtual DbSet<I_InventoryRecord> I_InventoryRecord { get; set; }
        public virtual DbSet<I_Storage> I_Storage { get; set; }
        public virtual DbSet<I_StoragePerson> I_StoragePerson { get; set; }
        public virtual DbSet<I_StorageRole> I_StorageRole { get; set; }
        public virtual DbSet<I_Surplus> I_Surplus { get; set; }
        public virtual DbSet<M_ZICDNew> M_ZICDNew { get; set; }
        public virtual DbSet<M_ZCaseTemplate> M_ZCaseTemplate { get; set; }
        public virtual DbSet<I_ApplyDetail> I_ApplyDetail { get; set; }
        public virtual DbSet<I_Apply> I_Apply { get; set; }
        public virtual DbSet<M_PatientRecordAppend> M_PatientRecordAppend { get; set; }
        public virtual DbSet<M_PatientRecord> M_PatientRecord { get; set; }
        public virtual DbSet<I_Material> I_Material { get; set; }
        public virtual DbSet<M_PatientRecordRescue> M_PatientRecordRescue { get; set; }
        public virtual DbSet<M_PatientRecordDrug> M_PatientRecordDrug { get; set; }
        public virtual DbSet<M_PatientRecordLossDrug> M_PatientRecordLossDrug { get; set; }
        public virtual DbSet<M_PatientRecordLossSanitation> M_PatientRecordLossSanitation { get; set; }
        public virtual DbSet<M_PatientRecordMeasure> M_PatientRecordMeasure { get; set; }
        public virtual DbSet<M_PatientRecordSanitation> M_PatientRecordSanitation { get; set; }
        public virtual DbSet<I_BalanceList> I_BalanceList { get; set; }
        public virtual DbSet<I_Balance> I_Balance { get; set; }
    }
}
