//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Apply
    {
        public I_Apply()
        {
            this.I_ApplyDetail = new HashSet<I_ApplyDetail>();
        }
    
        public string ApplyCode { get; set; }
        public int ApplyUserID { get; set; }
        public int ApplyReceivingStoreID { get; set; }
        public System.DateTime ApplyTime { get; set; }
        public string ApplyType { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ApprovalUserID { get; set; }
        public Nullable<System.DateTime> ApprovalTime { get; set; }
    
        public virtual I_Storage I_Storage { get; set; }
        public virtual P_User P_User { get; set; }
        public virtual P_User P_User1 { get; set; }
        public virtual TDictionary TDictionary { get; set; }
        public virtual ICollection<I_ApplyDetail> I_ApplyDetail { get; set; }
    }
}
