//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Delivery
    {
        public I_Delivery()
        {
            this.I_DeliveryDetail = new HashSet<I_DeliveryDetail>();
        }
    
        public string DeliveryCode { get; set; }
        public string ConsigneeID { get; set; }
        public System.DateTime DeliveryTime { get; set; }
        public string Remark { get; set; }
        public int OperatorCode { get; set; }
        public System.DateTime OperationTime { get; set; }
        public int ReceivingStoreID { get; set; }
        public string DeliveryType { get; set; }
    
        public virtual I_Storage I_Storage { get; set; }
        public virtual P_User P_User { get; set; }
        public virtual TDictionary TDictionary { get; set; }
        public virtual ICollection<I_DeliveryDetail> I_DeliveryDetail { get; set; }
    }
}
