//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_DeliveryDetail
    {
        public I_DeliveryDetail()
        {
            this.I_InventoryRecord = new HashSet<I_InventoryRecord>();
        }
    
        public string DeliveryDetailCode { get; set; }
        public string DeliveryCode { get; set; }
        public int EntryStorageCode { get; set; }
        public int MaterialID { get; set; }
        public string RealBatchNo { get; set; }
        public string BatchNo { get; set; }
        public System.DateTime DeliveryTime { get; set; }
        public double DeliveryCounts { get; set; }
        public int OperatorCode { get; set; }
        public int TargetStorageCode { get; set; }
        public string TargetEntryDetailCode { get; set; }
        public string Remark { get; set; }
        public string RedDeliveryDetailCode { get; set; }
    
        public virtual I_Delivery I_Delivery { get; set; }
        public virtual I_Storage I_Storage { get; set; }
        public virtual I_Storage I_Storage1 { get; set; }
        public virtual P_User P_User { get; set; }
        public virtual ICollection<I_InventoryRecord> I_InventoryRecord { get; set; }
        public virtual I_Material I_Material { get; set; }
    }
}
