//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Entry
    {
        public I_Entry()
        {
            this.I_EntryDetail = new HashSet<I_EntryDetail>();
        }
    
        public string EntryCode { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Remark { get; set; }
        public int OperatorCode { get; set; }
        public System.DateTime OperationTime { get; set; }
        public string EntryType { get; set; }
        public int EntryStorageID { get; set; }
    
        public virtual I_Storage I_Storage { get; set; }
        public virtual P_User P_User { get; set; }
        public virtual TDictionary TDictionary { get; set; }
        public virtual ICollection<I_EntryDetail> I_EntryDetail { get; set; }
    }
}
