//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_EntryDetail
    {
        public I_EntryDetail()
        {
            this.I_InventoryRecord = new HashSet<I_InventoryRecord>();
        }
    
        public string EntryDetailCode { get; set; }
        public string EntryCode { get; set; }
        public int MaterialID { get; set; }
        public string RealBatchNo { get; set; }
        public string BatchNo { get; set; }
        public System.DateTime EntryDate { get; set; }
        public double EntryCounts { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime ValidityDate { get; set; }
        public int OperatorCode { get; set; }
        public int StorageCode { get; set; }
        public string Remark { get; set; }
        public string Specification { get; set; }
        public string Unit { get; set; }
        public string RelatedOrderNum { get; set; }
        public string RedEntryDetailCode { get; set; }
    
        public virtual I_Entry I_Entry { get; set; }
        public virtual I_Storage I_Storage { get; set; }
        public virtual P_User P_User { get; set; }
        public virtual ICollection<I_InventoryRecord> I_InventoryRecord { get; set; }
        public virtual I_Material I_Material { get; set; }
    }
}
