//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Storage
    {
        public I_Storage()
        {
            this.I_Delivery = new HashSet<I_Delivery>();
            this.I_DeliveryDetail = new HashSet<I_DeliveryDetail>();
            this.I_DeliveryDetail1 = new HashSet<I_DeliveryDetail>();
            this.I_Entry = new HashSet<I_Entry>();
            this.I_EntryDetail = new HashSet<I_EntryDetail>();
            this.I_InventoryRecord = new HashSet<I_InventoryRecord>();
            this.I_StoragePerson = new HashSet<I_StoragePerson>();
            this.I_Surplus = new HashSet<I_Surplus>();
            this.I_ApplyDetail = new HashSet<I_ApplyDetail>();
            this.I_ApplyDetail1 = new HashSet<I_ApplyDetail>();
            this.I_ApplyDetail2 = new HashSet<I_ApplyDetail>();
            this.I_Apply = new HashSet<I_Apply>();
        }
    
        public int StorageID { get; set; }
        public string ParentStorageID { get; set; }
        public string Name { get; set; }
        public int LinkSign { get; set; }
        public string LinkCode { get; set; }
        public string Remark { get; set; }
        public int LevelCode { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<I_Delivery> I_Delivery { get; set; }
        public virtual ICollection<I_DeliveryDetail> I_DeliveryDetail { get; set; }
        public virtual ICollection<I_DeliveryDetail> I_DeliveryDetail1 { get; set; }
        public virtual ICollection<I_Entry> I_Entry { get; set; }
        public virtual ICollection<I_EntryDetail> I_EntryDetail { get; set; }
        public virtual ICollection<I_InventoryRecord> I_InventoryRecord { get; set; }
        public virtual ICollection<I_StoragePerson> I_StoragePerson { get; set; }
        public virtual ICollection<I_Surplus> I_Surplus { get; set; }
        public virtual ICollection<I_ApplyDetail> I_ApplyDetail { get; set; }
        public virtual ICollection<I_ApplyDetail> I_ApplyDetail1 { get; set; }
        public virtual ICollection<I_ApplyDetail> I_ApplyDetail2 { get; set; }
        public virtual ICollection<I_Apply> I_Apply { get; set; }
    }
}
