//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_StoragePerson
    {
        public int UserID { get; set; }
        public int StorageID { get; set; }
        public string Remark { get; set; }
    
        public virtual I_Storage I_Storage { get; set; }
        public virtual P_User P_User { get; set; }
    }
}
