//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Surplus
    {
        public int ID { get; set; }
        public int MaterialID { get; set; }
        public string RealBatchNo { get; set; }
        public string BatchNo { get; set; }
        public double EntryCounts { get; set; }
        public double Surplus { get; set; }
        public decimal SurplusPrice { get; set; }
        public int StorageCode { get; set; }
        public System.DateTime ValidityDate { get; set; }
    
        public virtual I_Storage I_Storage { get; set; }
        public virtual I_Material I_Material { get; set; }
    }
}
