//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Dictionary
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string TypeID { get; set; }
        public int SN { get; set; }
        public bool IsActive { get; set; }
    }
}
