//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PatientRecordMeasure
    {
        public string TaskCode { get; set; }
        public int PatientOrder { get; set; }
        public string RescueRecordCode { get; set; }
        public int RescueMeasureCode { get; set; }
        public int DisposeOrder { get; set; }
        public string RescueMeasureName { get; set; }
        public string OtherTypeID { get; set; }
        public Nullable<int> NumberOfTimes { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string ChargeWay { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SelectOrder { get; set; }
    }
}
