//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PatientRecordTrace
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ModifyPerson { get; set; }
        public string TaskCode { get; set; }
        public Nullable<int> PatientOrder { get; set; }
        public string ModifyItem { get; set; }
        public string OriginalValue { get; set; }
        public string NewValue { get; set; }
        public int OwnershipType { get; set; }
    }
}
