//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PatientRecordAppend
    {
        public string TaskCode { get; set; }
        public int PatientOrder { get; set; }
        public string DischargeDiagnosis { get; set; }
        public string HospitalMeasuresTreatment { get; set; }
        public string AtPresentPatientSymptom { get; set; }
        public string PhysicalExaminationChoose { get; set; }
        public string TChoose { get; set; }
        public string T { get; set; }
        public string PChoose { get; set; }
        public string P { get; set; }
        public string RChoose { get; set; }
        public string R { get; set; }
        public string BPChoose { get; set; }
        public string BP1 { get; set; }
        public string BP2 { get; set; }
        public string BP3 { get; set; }
        public string BP4 { get; set; }
        public string Consciousness { get; set; }
        public string Pupilla { get; set; }
        public string PupillaSupplement { get; set; }
        public string LightReflex { get; set; }
        public string LightReflexSupplement { get; set; }
        public string Skin { get; set; }
        public string SkinSupplement { get; set; }
        public string Head { get; set; }
        public string HeadSupplement { get; set; }
        public string Neck { get; set; }
        public string NeckSupplement { get; set; }
        public string Chest { get; set; }
        public string ChestExtrusionTest { get; set; }
        public string ChestSupplement { get; set; }
        public string Lungs { get; set; }
        public string TwoLungBreathingSound { get; set; }
        public string LeftLung { get; set; }
        public string RightLung { get; set; }
        public string LungsSupplement { get; set; }
        public string Heart { get; set; }
        public string HeartRate { get; set; }
        public string HeartRhythm { get; set; }
        public string HeartMurmur { get; set; }
        public string HeartSupplement { get; set; }
        public string Abdomen { get; set; }
        public string AbdomenSupplement { get; set; }
        public string Spine { get; set; }
        public string SpineSupplement { get; set; }
        public string Limbs { get; set; }
        public string PelvicExtrusionTest { get; set; }
        public string LimbsSupplement { get; set; }
        public string NervousSystem { get; set; }
        public string NervousSystemSupplement { get; set; }
        public string NervousSystemFace { get; set; }
        public string NervousSystemSpeech { get; set; }
        public string LeftUpperExtremity { get; set; }
        public string LeftLowerExtremity { get; set; }
        public string RightUpperLimb { get; set; }
        public string RightLowerLimb { get; set; }
        public string MuscularTension { get; set; }
        public string BabinskiSign { get; set; }
        public string ObstetricExamination { get; set; }
        public string GongGaoCartilagoEnsiformis { get; set; }
        public string GongGaoNavel { get; set; }
        public string GongGaoSuprapubic { get; set; }
        public string GongGaoBelowUmbilicus { get; set; }
        public string ObstetricExaminationSupplement { get; set; }
        public string PhysicalExaminationSupplement { get; set; }
        public string OtherNecessaryRecord { get; set; }
        public string OpenReaction { get; set; }
        public Nullable<double> OpenReactionScore { get; set; }
        public string LanguageReaction { get; set; }
        public Nullable<double> LanguageReactionScore { get; set; }
        public string MotionResponse { get; set; }
        public Nullable<double> MotionResponseScore { get; set; }
        public Nullable<double> GCSScore { get; set; }
        public string Position { get; set; }
        public Nullable<double> PositionScore { get; set; }
        public string DamageWay { get; set; }
        public Nullable<double> DamageWayScore { get; set; }
        public string CirculationChange { get; set; }
        public Nullable<double> CirculationChangeScore { get; set; }
        public string BreathingChange { get; set; }
        public Nullable<double> BreathingChangeScore { get; set; }
        public string ConsciousnessChange { get; set; }
        public Nullable<double> ConsciousnessChangeScore { get; set; }
        public Nullable<double> TIScore { get; set; }
        public string HeartRatePerMinute { get; set; }
        public Nullable<double> HeartRatePerMinuteScore { get; set; }
        public string Breathing { get; set; }
        public Nullable<double> BreathingScore { get; set; }
        public string MuscleTension { get; set; }
        public Nullable<double> MuscleTensionScore { get; set; }
        public string LaryngealReflex { get; set; }
        public Nullable<double> LaryngealReflexScore { get; set; }
        public string SkinColor { get; set; }
        public Nullable<double> SkinColorScore { get; set; }
        public Nullable<double> ApgarScore { get; set; }
        public string SymptomPendingInvestigation { get; set; }
        public string SymptomPendingInvestigationCodes { get; set; }
        public string SymptomPendingInvestigationSupplement { get; set; }
        public string FirstImpression { get; set; }
        public string FirstImpressionCodes { get; set; }
        public string FirstImpressionSupplement { get; set; }
        public string ECGImpressionSelect { get; set; }
        public string ECGImpression { get; set; }
        public string ECGImpressionCodes { get; set; }
        public string ECGImpressionSupplement { get; set; }
        public string ECGImpressionRetestI { get; set; }
        public string ECGImpressionRetestICodes { get; set; }
        public string ECGImpressionRetestISupplement { get; set; }
        public string ECGImpressionRetestII { get; set; }
        public string ECGImpressionRetestIICodes { get; set; }
        public string ECGImpressionRetestIISupplement { get; set; }
        public string BloodSugarSelect { get; set; }
        public string BloodSugar { get; set; }
        public string BloodSugarRetestI { get; set; }
        public string BloodSugarRetestII { get; set; }
        public string BloodOxygenSaturationSelect { get; set; }
        public string BloodOxygenSaturation { get; set; }
        public string BloodOxygenSaturationRetestI { get; set; }
        public string BloodOxygenSaturationRetestII { get; set; }
    }
}
