//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PatientRecordECGImpressions
    {
        public string TaskCode { get; set; }
        public int PatientOrder { get; set; }
        public int ECGImpressionsCode { get; set; }
        public Nullable<int> SelectOrder { get; set; }
    }
}
