//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PatientCharge
    {
        public string TaskCode { get; set; }
        public int PatientOrder { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string InvoiceNumber { get; set; }
        public string PatientName { get; set; }
        public string AddressStart { get; set; }
        public string AddressEnd { get; set; }
        public Nullable<double> OutStationRoadCode { get; set; }
        public Nullable<double> PointRoadCode { get; set; }
        public Nullable<double> ArriveHospitalRoadCode { get; set; }
        public Nullable<double> ReturnStationRoadCode { get; set; }
        public Nullable<double> OneWayKM { get; set; }
        public Nullable<double> ChargeKM { get; set; }
        public Nullable<double> CarFee { get; set; }
        public Nullable<double> WaitingFee { get; set; }
        public Nullable<double> EmergencyFee { get; set; }
        public Nullable<double> DrugFeeTotal { get; set; }
        public Nullable<double> ExamineFeeTotal { get; set; }
        public Nullable<double> ConsumableFeeTotal { get; set; }
        public Nullable<double> MeasureFeeTotal { get; set; }
        public Nullable<double> ReceivableTotal { get; set; }
        public Nullable<double> PaidMoney { get; set; }
        public string ChargePerson { get; set; }
        public Nullable<bool> IFArrearage { get; set; }
        public string TaskSD { get; set; }
    }
}
