//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PatientRecordCPR
    {
        public string TaskCode { get; set; }
        public int PatientOrder { get; set; }
        public string Witness { get; set; }
        public string CarToBeforeCPR { get; set; }
        public string CarToBeforeDefibrillation { get; set; }
        public Nullable<int> EmergencyTime { get; set; }
        public Nullable<System.DateTime> ECGMonitoringTime { get; set; }
        public string CardiacArrestReason { get; set; }
        public string CardiacArrestReasonSupplement { get; set; }
        public string BeforeResuscitationECGDiagnosis { get; set; }
        public string BeforeResuscitationSaO2 { get; set; }
        public string AfterResuscitationBP { get; set; }
        public string AfterResuscitationSaO2 { get; set; }
        public Nullable<System.DateTime> PulsationAppearTime { get; set; }
        public Nullable<System.DateTime> BreatheAppearTime { get; set; }
        public string AfterResuscitationECGDiagnosis { get; set; }
        public string IFAdmittedToHospital { get; set; }
        public string IFLeaveHospital { get; set; }
        public Nullable<System.DateTime> LeaveHospitalDate { get; set; }
        public string LeaveHospitalCPC { get; set; }
        public string VerifyResults { get; set; }
        public string VerifyPerson { get; set; }
        public Nullable<System.DateTime> VerifyTime { get; set; }
        public string RegistrationPerson { get; set; }
        public Nullable<System.DateTime> RegistrationTime { get; set; }
        public string DoctorFollowUp { get; set; }
        public Nullable<bool> CenterIFAuditForXFFS { get; set; }
        public string CenterAuditPerson { get; set; }
        public Nullable<System.DateTime> CenterAuditTime { get; set; }
        public string CenterAuditResult { get; set; }
        public string CenterNotThroughReason { get; set; }
    }
}
