//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PatientRecord
    {
        public string TaskCode { get; set; }
        public int PatientOrder { get; set; }
        public string CallOrder { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public string Age { get; set; }
        public string AgeType { get; set; }
        public string ForHelpTelephone { get; set; }
        public string ContactTelephone { get; set; }
        public string PatientVersion { get; set; }
        public string OriginalTaskType { get; set; }
        public string EmptyReason { get; set; }
        public string EmptyReasonSupplement { get; set; }
        public string ForArea { get; set; }
        public string LocalAddress { get; set; }
        public string OutStationCode { get; set; }
        public string Station { get; set; }
        public string SendAddress { get; set; }
        public Nullable<System.DateTime> DrivingTime { get; set; }
        public Nullable<System.DateTime> ArriveSceneTime { get; set; }
        public Nullable<System.DateTime> LeaveSceneTime { get; set; }
        public Nullable<System.DateTime> ArriveDestinationTime { get; set; }
        public string Driver { get; set; }
        public string StretcherBearersI { get; set; }
        public string StretcherBearersII { get; set; }
        public string DoctorAndNurse { get; set; }
        public string TeachingPractice { get; set; }
        public string ProvideMedicalHistoryPeople { get; set; }
        public string DiseasesClassification { get; set; }
        public string DiseasesClassificationSupplement { get; set; }
        public string AlarmReason { get; set; }
        public string HistoryOfPresentIllness { get; set; }
        public string PastMedicalHistory { get; set; }
        public string PastMedicalHistorySupplement { get; set; }
        public string IllnessClassification { get; set; }
        public string IllnessForecast { get; set; }
        public string DeathCase { get; set; }
        public string DeathCertificate { get; set; }
        public string FirstAidEffect { get; set; }
        public string MajorEmergencies { get; set; }
        public string DiseaseCooperation { get; set; }
        public string DiseaseNotCooperationSupplement { get; set; }
        public string AgentCode { get; set; }
        public string AgentWorkID { get; set; }
        public string AgentName { get; set; }
        public Nullable<System.DateTime> BeginFillPatientTime { get; set; }
        public Nullable<System.DateTime> MedicalRecordGenerationTime { get; set; }
        public Nullable<bool> FormCompleteLogo { get; set; }
        public Nullable<System.DateTime> FormCompleteTime { get; set; }
        public Nullable<int> ChargeOrder { get; set; }
        public Nullable<bool> SubmitLogo { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public Nullable<bool> SubCenterIFSpotChecks { get; set; }
        public string SubCenterPerson { get; set; }
        public string SubCenterSpotChecksTime { get; set; }
        public string SubCenterSpotChecksResult { get; set; }
        public string SubCenterSpotChecksRmark { get; set; }
        public Nullable<bool> CenterIFSpotChecks { get; set; }
        public string CenterSpotChecksPerson { get; set; }
        public string CenterSpotChecksTime { get; set; }
        public string CenterSpotChecksResult { get; set; }
        public string CenterSpotChecksRmark { get; set; }
        public Nullable<int> MedicalStateCode { get; set; }
        public string LastUpdatePerson { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string CPRIFSuccess { get; set; }
        public string IFRefuseTreatment { get; set; }
        public string RescueType { get; set; }
        public string IMEI { get; set; }
        public string Remark { get; set; }
    }
}
