//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Department
    {
        public P_Department()
        {
            this.P_Department1 = new HashSet<P_Department>();
            this.P_Role = new HashSet<P_Role>();
            this.P_User = new HashSet<P_User>();
        }
    
        public int ID { get; set; }
        public int ParentID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public int SN { get; set; }
        public string DispatchSationID { get; set; }
        public string DispatchSubCenterID { get; set; }
    
        public virtual ICollection<P_Department> P_Department1 { get; set; }
        public virtual P_Department P_Department2 { get; set; }
        public virtual ICollection<P_Role> P_Role { get; set; }
        public virtual ICollection<P_User> P_User { get; set; }
    }
}
