//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Permission
    {
        public P_Permission()
        {
            this.P_RolePermission = new HashSet<P_RolePermission>();
            this.P_SpeicalPermission = new HashSet<P_SpeicalPermission>();
        }
    
        public int ID { get; set; }
        public int ParentID { get; set; }
        public string Name { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public short FormMethod { get; set; }
        public bool IsLink { get; set; }
        public string LinkURL { get; set; }
        public bool IsShow { get; set; }
        public string ICO { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public int SN { get; set; }
    
        public virtual ICollection<P_RolePermission> P_RolePermission { get; set; }
        public virtual ICollection<P_SpeicalPermission> P_SpeicalPermission { get; set; }
    }
}
