//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Role
    {
        public P_Role()
        {
            this.P_RolePermission = new HashSet<P_RolePermission>();
            this.P_UserRole = new HashSet<P_UserRole>();
            this.I_StorageRole = new HashSet<I_StorageRole>();
        }
    
        public int ID { get; set; }
        public int DepID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public int SN { get; set; }
    
        public virtual P_Department P_Department { get; set; }
        public virtual ICollection<P_RolePermission> P_RolePermission { get; set; }
        public virtual ICollection<P_UserRole> P_UserRole { get; set; }
        public virtual ICollection<I_StorageRole> I_StorageRole { get; set; }
    }
}
