//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_User
    {
        public P_User()
        {
            this.P_SpeicalPermission = new HashSet<P_SpeicalPermission>();
            this.P_UserRole = new HashSet<P_UserRole>();
            this.I_Delivery = new HashSet<I_Delivery>();
            this.I_DeliveryDetail = new HashSet<I_DeliveryDetail>();
            this.I_Entry = new HashSet<I_Entry>();
            this.I_EntryDetail = new HashSet<I_EntryDetail>();
            this.I_InventoryRecord = new HashSet<I_InventoryRecord>();
            this.I_StoragePerson = new HashSet<I_StoragePerson>();
            this.I_ApplyDetail = new HashSet<I_ApplyDetail>();
            this.I_Apply = new HashSet<I_Apply>();
            this.I_Apply1 = new HashSet<I_Apply>();
        }
    
        public int ID { get; set; }
        public int DepID { get; set; }
        public string LoginName { get; set; }
        public string PassWord { get; set; }
        public string WorkCode { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public bool IsActive { get; set; }
        public int SN { get; set; }
    
        public virtual P_Department P_Department { get; set; }
        public virtual ICollection<P_SpeicalPermission> P_SpeicalPermission { get; set; }
        public virtual ICollection<P_UserRole> P_UserRole { get; set; }
        public virtual ICollection<I_Delivery> I_Delivery { get; set; }
        public virtual ICollection<I_DeliveryDetail> I_DeliveryDetail { get; set; }
        public virtual ICollection<I_Entry> I_Entry { get; set; }
        public virtual ICollection<I_EntryDetail> I_EntryDetail { get; set; }
        public virtual ICollection<I_InventoryRecord> I_InventoryRecord { get; set; }
        public virtual ICollection<I_StoragePerson> I_StoragePerson { get; set; }
        public virtual ICollection<I_ApplyDetail> I_ApplyDetail { get; set; }
        public virtual ICollection<I_Apply> I_Apply { get; set; }
        public virtual ICollection<I_Apply> I_Apply1 { get; set; }
    }
}
