//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.SHManage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDictionary
    {
        public TDictionary()
        {
            this.I_Delivery = new HashSet<I_Delivery>();
            this.I_Entry = new HashSet<I_Entry>();
            this.I_StorageRole = new HashSet<I_StorageRole>();
            this.I_Apply = new HashSet<I_Apply>();
            this.I_Material = new HashSet<I_Material>();
            this.I_Material1 = new HashSet<I_Material>();
            this.I_Material2 = new HashSet<I_Material>();
            this.I_BalanceList = new HashSet<I_BalanceList>();
        }
    
        public string ID { get; set; }
        public string Name { get; set; }
        public string TypeID { get; set; }
        public int SN { get; set; }
        public bool IsActive { get; set; }
        public string ParentID { get; set; }
    
        public virtual ICollection<I_Delivery> I_Delivery { get; set; }
        public virtual ICollection<I_Entry> I_Entry { get; set; }
        public virtual ICollection<I_StorageRole> I_StorageRole { get; set; }
        public virtual ICollection<I_Apply> I_Apply { get; set; }
        public virtual ICollection<I_Material> I_Material { get; set; }
        public virtual ICollection<I_Material> I_Material1 { get; set; }
        public virtual ICollection<I_Material> I_Material2 { get; set; }
        public virtual ICollection<I_BalanceList> I_BalanceList { get; set; }
    }
}
