//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class I_Apply
	{
		public I_Apply ToPOCO(bool isPOCO = true){
			return new I_Apply(){
				ApplyCode = this.ApplyCode,
				ApplyUserID = this.ApplyUserID,
				ApplyReceivingStoreID = this.ApplyReceivingStoreID,
				ApplyTime = this.ApplyTime,
				ApplyType = this.ApplyType,
				Remark = this.Remark,
				ApprovalUserID = this.ApprovalUserID,
				ApprovalTime = this.ApprovalTime,
			};
		}
	}
}
