//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class I_Balance
	{
        public string MName { get; set; }
		public I_Balance ToPOCO(bool isPOCO = true){
			return new I_Balance(){
				MaterialID = this.MaterialID,
				ReportTime = this.ReportTime,
				BeginningCounts = this.BeginningCounts,
				BeginningPrice = this.BeginningPrice,
				IncomeCounts = this.IncomeCounts,
				IncomePrice = this.IncomePrice,
				PayCounts = this.PayCounts,
				PayPrice = this.PayPrice,
				UpdataPrice = this.UpdataPrice,
				SurplusCounts = this.SurplusCounts,
				SurplusPrice = this.SurplusPrice,
				SurplusTime = this.SurplusTime,
                MName = this.MName,
			};
		}
	}
}
