//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class I_EntryDetail
	{
		public I_EntryDetail ToPOCO(bool isPOCO = true){
			return new I_EntryDetail(){
				EntryDetailCode = this.EntryDetailCode,
				EntryCode = this.EntryCode,
				MaterialID = this.MaterialID,
				RealBatchNo = this.RealBatchNo,
				BatchNo = this.BatchNo,
				EntryDate = this.EntryDate,
				EntryCounts = this.EntryCounts,
				TotalPrice = this.TotalPrice,
				ValidityDate = this.ValidityDate,
				OperatorCode = this.OperatorCode,
				StorageCode = this.StorageCode,
				Remark = this.Remark,
				Specification = this.Specification,
				Unit = this.Unit,
				RelatedOrderNum = this.RelatedOrderNum,
				RedEntryDetailCode = this.RedEntryDetailCode,
			};
		}
	}
}
