//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class I_InventoryRecord
	{
		public I_InventoryRecord ToPOCO(bool isPOCO = true){
			return new I_InventoryRecord(){
				ID = this.ID,
				MaterialID = this.MaterialID,
				Is_Entry = this.Is_Entry,
				EntryDetailCode = this.EntryDetailCode,
				DeliveryDetailCode = this.DeliveryDetailCode,
				OperatorDateTime = this.OperatorDateTime,
				StorageCode = this.StorageCode,
				OriginalSurplus = this.OriginalSurplus,
				ChangeSurplus = this.ChangeSurplus,
				Surplus = this.Surplus,
				SurplusPrice = this.SurplusPrice,
				BatchNo = this.BatchNo,
				RealBatchNo = this.RealBatchNo,
				DeliveryEntryType = this.DeliveryEntryType,
				OperatorCode = this.OperatorCode,
			};
		}
	}
}
