//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class I_Storage
	{
		public I_Storage ToPOCO(bool isPOCO = true){
			return new I_Storage(){
				StorageID = this.StorageID,
				ParentStorageID = this.ParentStorageID,
				Name = this.Name,
				LinkSign = this.LinkSign,
				LinkCode = this.LinkCode,
				Remark = this.Remark,
				LevelCode = this.LevelCode,
				IsActive = this.IsActive,
			};
		}
	}
}
