//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class M_PatientRecord
	{
		public M_PatientRecord ToPOCO(bool isPOCO = true){
			return new M_PatientRecord(){
				TaskCode = this.TaskCode,
				PatientOrder = this.PatientOrder,
				CallOrder = this.CallOrder,
				Name = this.Name,
				Sex = this.Sex,
				Age = this.Age,
				AgeType = this.AgeType,
				ForHelpTelephone = this.ForHelpTelephone,
				ContactTelephone = this.ContactTelephone,
				PatientVersion = this.PatientVersion,
				OriginalTaskType = this.OriginalTaskType,
				EmptyReason = this.EmptyReason,
				EmptyReasonSupplement = this.EmptyReasonSupplement,
				ForArea = this.ForArea,
				LocalAddress = this.LocalAddress,
				OutStationCode = this.OutStationCode,
				Station = this.Station,
				SendAddress = this.SendAddress,
				DrivingTime = this.DrivingTime,
				ArriveSceneTime = this.ArriveSceneTime,
				LeaveSceneTime = this.LeaveSceneTime,
				ArriveDestinationTime = this.ArriveDestinationTime,
				Driver = this.Driver,
				StretcherBearersI = this.StretcherBearersI,
				StretcherBearersII = this.StretcherBearersII,
				DoctorAndNurse = this.DoctorAndNurse,
				TeachingPractice = this.TeachingPractice,
				ProvideMedicalHistoryPeople = this.ProvideMedicalHistoryPeople,
				DiseasesClassification = this.DiseasesClassification,
				DiseasesClassificationSupplement = this.DiseasesClassificationSupplement,
				AlarmReason = this.AlarmReason,
				HistoryOfPresentIllness = this.HistoryOfPresentIllness,
				PastMedicalHistory = this.PastMedicalHistory,
				PastMedicalHistorySupplement = this.PastMedicalHistorySupplement,
				IllnessClassification = this.IllnessClassification,
				IllnessForecast = this.IllnessForecast,
				DeathCase = this.DeathCase,
				DeathCertificate = this.DeathCertificate,
				FirstAidEffect = this.FirstAidEffect,
				MajorEmergencies = this.MajorEmergencies,
				DiseaseCooperation = this.DiseaseCooperation,
				DiseaseNotCooperationSupplement = this.DiseaseNotCooperationSupplement,
				AgentCode = this.AgentCode,
				AgentWorkID = this.AgentWorkID,
				AgentName = this.AgentName,
				BeginFillPatientTime = this.BeginFillPatientTime,
				MedicalRecordGenerationTime = this.MedicalRecordGenerationTime,
				FormCompleteLogo = this.FormCompleteLogo,
				FormCompleteTime = this.FormCompleteTime,
				ChargeOrder = this.ChargeOrder,
				SubmitLogo = this.SubmitLogo,
				SubmitTime = this.SubmitTime,
				SubCenterIFSpotChecks = this.SubCenterIFSpotChecks,
				SubCenterPerson = this.SubCenterPerson,
				SubCenterSpotChecksTime = this.SubCenterSpotChecksTime,
				SubCenterSpotChecksResult = this.SubCenterSpotChecksResult,
				SubCenterSpotChecksRmark = this.SubCenterSpotChecksRmark,
				CenterIFSpotChecks = this.CenterIFSpotChecks,
				CenterSpotChecksPerson = this.CenterSpotChecksPerson,
				CenterSpotChecksTime = this.CenterSpotChecksTime,
				CenterSpotChecksResult = this.CenterSpotChecksResult,
				CenterSpotChecksRmark = this.CenterSpotChecksRmark,
				MedicalStateCode = this.MedicalStateCode,
				LastUpdatePerson = this.LastUpdatePerson,
				LastUpdateTime = this.LastUpdateTime,
				CPRIFSuccess = this.CPRIFSuccess,
				IFRefuseTreatment = this.IFRefuseTreatment,
				RescueType = this.RescueType,
				IMEI = this.IMEI,
				Remark = this.Remark,
			};
		}
	}
}
