//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class M_PatientRecordSanitation
	{
		public M_PatientRecordSanitation ToPOCO(bool isPOCO = true){
			return new M_PatientRecordSanitation(){
				TaskCode = this.TaskCode,
				PatientOrder = this.PatientOrder,
				RescueRecordCode = this.RescueRecordCode,
				SanitationCode = this.SanitationCode,
				DisposeOrder = this.DisposeOrder,
				SanitationName = this.SanitationName,
				NumberOfTimes = this.NumberOfTimes,
				Price = this.Price,
				TotalPrice = this.TotalPrice,
				ChargeWay = this.ChargeWay,
				Remark = this.Remark,
				SelectOrder = this.SelectOrder,
			};
		}
	}
}
