//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class M_PatientRecordDiag
	{
		public M_PatientRecordDiag ToPOCO(bool isPOCO = true){
			return new M_PatientRecordDiag(){
				TaskCode = this.TaskCode,
				PatientOrder = this.PatientOrder,
				PrimaryDiagnosisCode = this.PrimaryDiagnosisCode,
				SelectOrder = this.SelectOrder,
			};
		}
	}
}
