//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class M_PatientRecordDrug
	{
		public M_PatientRecordDrug ToPOCO(bool isPOCO = true){
			return new M_PatientRecordDrug(){
				TaskCode = this.TaskCode,
				PatientOrder = this.PatientOrder,
				RescueRecordCode = this.RescueRecordCode,
				DrugCode = this.DrugCode,
				DisposeOrder = this.DisposeOrder,
				DrugName = this.DrugName,
				GiveMedicineWay = this.GiveMedicineWay,
				ChargeWay = this.ChargeWay,
				Specifications = this.Specifications,
				Unit = this.Unit,
				Dosage = this.Dosage,
				Price = this.Price,
				TotalPrice = this.TotalPrice,
				TotalDose = this.TotalDose,
				Remark = this.Remark,
				SelectOrder = this.SelectOrder,
				FeeScale = this.FeeScale,
			};
		}
	}
}
