//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class M_PatientCharge
	{
		public M_PatientCharge ToPOCO(bool isPOCO = true){
			return new M_PatientCharge(){
				TaskCode = this.TaskCode,
				PatientOrder = this.PatientOrder,
				Date = this.Date,
				InvoiceNumber = this.InvoiceNumber,
				PatientName = this.PatientName,
				AddressStart = this.AddressStart,
				AddressEnd = this.AddressEnd,
				OutStationRoadCode = this.OutStationRoadCode,
				PointRoadCode = this.PointRoadCode,
				ArriveHospitalRoadCode = this.ArriveHospitalRoadCode,
				ReturnStationRoadCode = this.ReturnStationRoadCode,
				OneWayKM = this.OneWayKM,
				ChargeKM = this.ChargeKM,
				CarFee = this.CarFee,
				WaitingFee = this.WaitingFee,
				EmergencyFee = this.EmergencyFee,
				DrugFeeTotal = this.DrugFeeTotal,
				ExamineFeeTotal = this.ExamineFeeTotal,
				ConsumableFeeTotal = this.ConsumableFeeTotal,
				MeasureFeeTotal = this.MeasureFeeTotal,
				ReceivableTotal = this.ReceivableTotal,
				PaidMoney = this.PaidMoney,
				ChargePerson = this.ChargePerson,
				IFArrearage = this.IFArrearage,
				TaskSD = this.TaskSD,
			};
		}
	}
}
