//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class M_PatientRecordRescue
	{
		public M_PatientRecordRescue ToPOCO(bool isPOCO = true){
			return new M_PatientRecordRescue(){
				TaskCode = this.TaskCode,
				PatientOrder = this.PatientOrder,
				RescueRecordCode = this.RescueRecordCode,
				DisposeOrder = this.DisposeOrder,
				PeriodOfTime = this.PeriodOfTime,
				PeriodOfTimeCode = this.PeriodOfTimeCode,
				Measures = this.Measures,
				MeasureCodes = this.MeasureCodes,
				Drugs = this.Drugs,
				DrugCodes = this.DrugCodes,
				Sanitations = this.Sanitations,
				SanitationCodes = this.SanitationCodes,
				Remark = this.Remark,
				LossDrugs = this.LossDrugs,
				LossDrugCodes = this.LossDrugCodes,
				LossSanitations = this.LossSanitations,
				LossSanitationCodes = this.LossSanitationCodes,
				DiseaseIFChanges = this.DiseaseIFChanges,
				DiseaseChangesSupplement = this.DiseaseChangesSupplement,
				LastUpdatePerson = this.LastUpdatePerson,
				LastUpdateTime = this.LastUpdateTime,
				RescueXFFSMouldChoose = this.RescueXFFSMouldChoose,
			};
		}
	}
}
