//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class P_Permission
	{
		public P_Permission ToPOCO(bool isPOCO = true){
			return new P_Permission(){
				ID = this.ID,
				ParentID = this.ParentID,
				Name = this.Name,
				AreaName = this.AreaName,
				ControllerName = this.ControllerName,
				ActionName = this.ActionName,
				FormMethod = this.FormMethod,
				IsLink = this.IsLink,
				LinkURL = this.LinkURL,
				IsShow = this.IsShow,
				ICO = this.ICO,
				Remark = this.Remark,
				IsActive = this.IsActive,
				SN = this.SN,
			};
		}
	}
}
