//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Anke.SHManage.Model
{
	public partial class P_User
	{
		public P_User ToPOCO(bool isPOCO = true){
			return new P_User(){
				ID = this.ID,
				DepID = this.DepID,
				LoginName = this.LoginName,
				PassWord = this.PassWord,
				WorkCode = this.WorkCode,
				Name = this.Name,
				Gender = this.Gender,
				IsActive = this.IsActive,
				SN = this.SN,
			};
		}
	}
}
