//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anke.AnkeOAService
{
    using System;
    using System.Collections.Generic;

    public partial class P_User
    {
        public int ID { get; set; }
        public int DepID { get; set; }
        public int RoleID { get; set; }
        public string LoginName { get; set; }
        public string PassWord { get; set; }
        public string WorkCode { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public bool IsActive { get; set; }
        public int SN { get; set; }
    }
}
